---
- hosts: webservers
  vars:
    certbot_install_method: snap
    certbot_create_if_missing: true
    certbot_admin_email: dencic.pavle@gmail.com
    certbot_certs:
    - domains:
        - "{{ domain }}"
  roles:
  - role: geerlingguy.certbot
    become: yes