---
- hosts: dockers
  pre_tasks:
     - name: update repositories cache
       become: yes
       apt:
           update_cache: yes
  collections:
     - community.docker
  roles:
     - install_docker
  tasks:
  - name: make sure we got pip
    become: yes
    apt:
      name: pip
      state: present

  - name: install docker sdk
    pip:
      name: docker

  - name: make sure docker is running
    service:
      name: docker
      state: started

  - name: deploy docker images
    block:
      - name: deploy docker-telegram-notifier
        community.docker.docker_container:
          name: telegram-notifier
          image: lorcas/docker-telegram-notifier
          env:
            TELEGRAM_NOTIFIER_BOT_TOKEN: "{{ docker_alerts_token }}"
            TELEGRAM_NOTIFIER_CHAT_ID: "{{ docker_alerts_channel }}"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
          restart_policy: "unless-stopped"
