---
- name: uninstall old versions 
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd.io
      - runc
    state: absent

- name: set up the repository
  apt: 
    name: 
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: add docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present 
    
- name: register dpkg architecture name
  shell: dpkg --print-architecture
  register: arch

- name: set up docker apt repository 
  apt_repository:
    repo: "deb [arch={{ arch.stdout }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_version | default('stable')}}"
    state: present

- name: update apt cache
  apt:
    update_cache: yes

- name: install docker engine
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: add user to docker group
  become: yes
  user: 
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes